### ISSUE TITLE
使用slide方式展示分享，点击更多没有反应没弹出框，button方式正常

### ISSUE THREAD

**Issue by shaipxiang** [hrwhisper/baiduShare#8]
使用slide方式展示分享，点击更多没有反应
问题如下：
pop_dialog.js?v=d479767d.js:1 Uncaught TypeError: Cannot read property 'name' of undefined
我对前端了解不多，请帮助解决

**Comment by hrwhisper** [comment]
不知道你什么情况，在自己的wordpress博客以及github的hexo上都测试良好https://murmured.github.io/2017/05/08/baiduShare2/
